-- password : 123123123
--test
INSERT INTO t_user (full_name, password, username, role, status, branch_work_id) VALUES
('Administrator','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','1231231231','ROLE_ADMIN','ACTIVE',''),
('Manager Test','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','1231231232','ROLE_MANAGER','ACTIVE','1'),
('Shipper Test','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','1231231233','ROLE_SHIPPER','ACTIVE','1');
INSERT INTO t_user (full_name, password, username, role, status, branch_work_id, email) VALUES
('Customer Test','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','1231231234','ROLE_CUSTOMER','ACTIVE','','nguyenthanhtaiabcxyz@gmail.com');
-- test doi mat khau
--INSERT INTO `t_user` (full_name, password, username, role, status, branch_work_id,email) VALUES
--('Administrator','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','12312312311','ROLE_ADMIN','ACTIVE','','nguyenthanhtaiabcxyz@gmail.com');
--manager
INSERT INTO t_user (full_name, password, username, role, status, branch_work_id) VALUES
('manager1','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager1','ROLE_MANAGER','ACTIVE','1'),
('manager2','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager2','ROLE_MANAGER','ACTIVE','2'),
('manager3','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager3','ROLE_MANAGER','ACTIVE','3'),
('manager4','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager4','ROLE_MANAGER','ACTIVE','4'),
('manager5','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager5','ROLE_MANAGER','ACTIVE','5'),
('manager6','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager6','ROLE_MANAGER','ACTIVE','6'),
('manager7','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager7','ROLE_MANAGER','ACTIVE','7'),
('manager8','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager8','ROLE_MANAGER','ACTIVE','8'),
('manager9','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager9','ROLE_MANAGER','ACTIVE','9'),
('manager10','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager10','ROLE_MANAGER','ACTIVE','10'),
('manager11','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager11','ROLE_MANAGER','ACTIVE','11'),
('manager12','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager12','ROLE_MANAGER','ACTIVE','12'),
('manager13','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager13','ROLE_MANAGER','ACTIVE','13'),
('manager14','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager14','ROLE_MANAGER','ACTIVE','14'),
('manager15','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager15','ROLE_MANAGER','ACTIVE','15'),
('manager16','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager16','ROLE_MANAGER','ACTIVE','16'),
('manager17','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager17','ROLE_MANAGER','ACTIVE','17'),
('manager18','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager18','ROLE_MANAGER','ACTIVE','18'),
('manager19','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager19','ROLE_MANAGER','ACTIVE','19'),
('manager20','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager20','ROLE_MANAGER','ACTIVE','20'),
('manager21','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager21','ROLE_MANAGER','ACTIVE','21'),
('manager22','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager22','ROLE_MANAGER','ACTIVE','22'),
('manager23','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager23','ROLE_MANAGER','ACTIVE','23'),
('manager24','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager24','ROLE_MANAGER','ACTIVE','24'),
('manager25','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager25','ROLE_MANAGER','ACTIVE','25'),
('manager26','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager26','ROLE_MANAGER','ACTIVE','26'),
('manager27','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager27','ROLE_MANAGER','ACTIVE','27'),
('manager28','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager28','ROLE_MANAGER','ACTIVE','28'),
('manager29','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager29','ROLE_MANAGER','ACTIVE','29'),
('manager30','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager30','ROLE_MANAGER','ACTIVE','30'),
('manager31','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager31','ROLE_MANAGER','ACTIVE','31'),
('manager32','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager32','ROLE_MANAGER','ACTIVE','32'),
('manager33','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager33','ROLE_MANAGER','ACTIVE','33'),
('manager34','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager34','ROLE_MANAGER','ACTIVE','34'),
('manager35','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager35','ROLE_MANAGER','ACTIVE','35'),
('manager36','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager36','ROLE_MANAGER','ACTIVE','36'),
('manager37','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager37','ROLE_MANAGER','ACTIVE','37'),
('manager38','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager38','ROLE_MANAGER','ACTIVE','38'),
('manager39','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager39','ROLE_MANAGER','ACTIVE','39'),
('manager40','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager40','ROLE_MANAGER','ACTIVE','40'),
('manager41','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager41','ROLE_MANAGER','ACTIVE','41'),
('manager42','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager42','ROLE_MANAGER','ACTIVE','42'),
('manager43','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager43','ROLE_MANAGER','ACTIVE','43'),
('manager44','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager44','ROLE_MANAGER','ACTIVE','44'),
('manager45','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager45','ROLE_MANAGER','ACTIVE','45'),
('manager46','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager46','ROLE_MANAGER','ACTIVE','46'),
('manager47','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager47','ROLE_MANAGER','ACTIVE','47'),
('manager48','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager48','ROLE_MANAGER','ACTIVE','48'),
('manager49','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager49','ROLE_MANAGER','ACTIVE','49'),
('manager50','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager50','ROLE_MANAGER','ACTIVE','50'),
('manager51','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager51','ROLE_MANAGER','ACTIVE','51'),
('manager52','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager52','ROLE_MANAGER','ACTIVE','52'),
('manager53','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager53','ROLE_MANAGER','ACTIVE','53'),
('manager54','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager54','ROLE_MANAGER','ACTIVE','54'),
('manager55','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager55','ROLE_MANAGER','ACTIVE','55'),
('manager56','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager56','ROLE_MANAGER','ACTIVE','56'),
('manager57','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager57','ROLE_MANAGER','ACTIVE','57'),
('manager58','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager58','ROLE_MANAGER','ACTIVE','58'),
('manager59','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager59','ROLE_MANAGER','ACTIVE','59'),
('manager60','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager60','ROLE_MANAGER','ACTIVE','60'),
('manager61','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager61','ROLE_MANAGER','ACTIVE','61'),
('manager62','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager62','ROLE_MANAGER','ACTIVE','62'),
('manager63','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','manager63','ROLE_MANAGER','ACTIVE','63');

--shipper
INSERT INTO t_user (full_name, password, username, role, status, branch_work_id) VALUES
('shipper1','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper1','ROLE_SHIPPER','ACTIVE','1'),
('shipper2','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper2','ROLE_SHIPPER','ACTIVE','2'),
('shipper3','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper3','ROLE_SHIPPER','ACTIVE','3'),
('shipper4','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper4','ROLE_SHIPPER','ACTIVE','4'),
('shipper5','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper5','ROLE_SHIPPER','ACTIVE','5'),
('shipper6','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper6','ROLE_SHIPPER','ACTIVE','6'),
('shipper7','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper7','ROLE_SHIPPER','ACTIVE','7'),
('shipper8','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper8','ROLE_SHIPPER','ACTIVE','8'),
('shipper9','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper9','ROLE_SHIPPER','ACTIVE','9'),
('shipper10','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper10','ROLE_SHIPPER','ACTIVE','10'),
('shipper11','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper11','ROLE_SHIPPER','ACTIVE','11'),
('shipper12','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper12','ROLE_SHIPPER','ACTIVE','12'),
('shipper13','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper13','ROLE_SHIPPER','ACTIVE','13'),
('shipper14','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper14','ROLE_SHIPPER','ACTIVE','14'),
('shipper15','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper15','ROLE_SHIPPER','ACTIVE','15'),
('shipper16','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper16','ROLE_SHIPPER','ACTIVE','16'),
('shipper17','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper17','ROLE_SHIPPER','ACTIVE','17'),
('shipper18','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper18','ROLE_SHIPPER','ACTIVE','18'),
('shipper19','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper19','ROLE_SHIPPER','ACTIVE','19'),
('shipper20','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper20','ROLE_SHIPPER','ACTIVE','20'),
('shipper21','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper21','ROLE_SHIPPER','ACTIVE','21'),
('shipper22','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper22','ROLE_SHIPPER','ACTIVE','22'),
('shipper23','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper23','ROLE_SHIPPER','ACTIVE','23'),
('shipper24','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper24','ROLE_SHIPPER','ACTIVE','24'),
('shipper25','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper25','ROLE_SHIPPER','ACTIVE','25'),
('shipper26','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper26','ROLE_SHIPPER','ACTIVE','26'),
('shipper27','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper27','ROLE_SHIPPER','ACTIVE','27'),
('shipper28','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper28','ROLE_SHIPPER','ACTIVE','28'),
('shipper29','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper29','ROLE_SHIPPER','ACTIVE','29'),
('shipper30','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper30','ROLE_SHIPPER','ACTIVE','30'),
('shipper31','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper31','ROLE_SHIPPER','ACTIVE','31'),
('shipper32','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper32','ROLE_SHIPPER','ACTIVE','32'),
('shipper33','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper33','ROLE_SHIPPER','ACTIVE','33'),
('shipper34','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper34','ROLE_SHIPPER','ACTIVE','34'),
('shipper35','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper35','ROLE_SHIPPER','ACTIVE','35'),
('shipper36','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper36','ROLE_SHIPPER','ACTIVE','36'),
('shipper37','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper37','ROLE_SHIPPER','ACTIVE','37'),
('shipper38','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper38','ROLE_SHIPPER','ACTIVE','38'),
('shipper39','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper39','ROLE_SHIPPER','ACTIVE','39'),
('shipper40','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper40','ROLE_SHIPPER','ACTIVE','40'),
('shipper41','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper41','ROLE_SHIPPER','ACTIVE','41'),
('shipper42','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper42','ROLE_SHIPPER','ACTIVE','42'),
('shipper43','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper43','ROLE_SHIPPER','ACTIVE','43'),
('shipper44','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper44','ROLE_SHIPPER','ACTIVE','44'),
('shipper45','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper45','ROLE_SHIPPER','ACTIVE','45'),
('shipper46','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper46','ROLE_SHIPPER','ACTIVE','46'),
('shipper47','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper47','ROLE_SHIPPER','ACTIVE','47'),
('shipper48','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper48','ROLE_SHIPPER','ACTIVE','48'),
('shipper49','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper49','ROLE_SHIPPER','ACTIVE','49'),
('shipper50','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper50','ROLE_SHIPPER','ACTIVE','50'),
('shipper51','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper51','ROLE_SHIPPER','ACTIVE','51'),
('shipper52','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper52','ROLE_SHIPPER','ACTIVE','52'),
('shipper53','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper53','ROLE_SHIPPER','ACTIVE','53'),
('shipper54','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper54','ROLE_SHIPPER','ACTIVE','54'),
('shipper55','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper55','ROLE_SHIPPER','ACTIVE','55'),
('shipper56','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper56','ROLE_SHIPPER','ACTIVE','56'),
('shipper57','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper57','ROLE_SHIPPER','ACTIVE','57'),
('shipper58','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper58','ROLE_SHIPPER','ACTIVE','58'),
('shipper59','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper59','ROLE_SHIPPER','ACTIVE','59'),
('shipper60','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper60','ROLE_SHIPPER','ACTIVE','60'),
('shipper61','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper61','ROLE_SHIPPER','ACTIVE','61'),
('shipper62','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper62','ROLE_SHIPPER','ACTIVE','62'),
('shipper63','$2a$10$.8CxwZDKcdtCG1bUlaIUCOSEAsRXwWGL5FT46jksGEtVkWprE9jjq','shipper63','ROLE_SHIPPER','ACTIVE','63');

INSERT INTO t_branch (name, province, district, ward, street, status, type) VALUES
('Chi nhánh An Giang', 'An Giang', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Bà Rịa - Vũng Tàu', 'Bà Rịa - Vũng Tàu', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Bạc Liêu', 'Bạc Liêu', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Bắc Giang', 'Bắc Giang', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Bắc Kạn', 'Bắc Kạn', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Bắc Ninh', 'Bắc Ninh', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Bến Tre', 'Bến Tre', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Bình Dương', 'Bình Dương', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Bình Định', 'Bình Định', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Bình Phước', 'Bình Phước', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Bình Thuận', 'Bình Thuận', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Cà Mau', 'Cà Mau', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Cao Bằng', 'Cao Bằng', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Cần Thơ', 'Cần Thơ', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Đà Nẵng', 'Đà Nẵng', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Đắk Lắk', 'Đắk Lắk', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Đắk Nông', 'Đắk Nông', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Điện Biên', 'Điện Biên', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Đồng Nai', 'Đồng Nai', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Đồng Tháp', 'Đồng Tháp', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Gia Lai', 'Gia Lai', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Hà Giang', 'Hà Giang', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Hà Nam', 'Hà Nam', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Hà Nội', 'Hà Nội', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Hà Tĩnh', 'Hà Tĩnh', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Hải Dương', 'Hải Dương', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Hải Phòng', 'Hải Phòng', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Hậu Giang', 'Hậu Giang', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Hòa Bình', 'Hòa Bình', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Hưng Yên', 'Hưng Yên', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Khánh Hòa', 'Khánh Hòa', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Kiên Giang', 'Kiên Giang', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Kon Tum', 'Kon Tum', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Lai Châu', 'Lai Châu', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Lâm Đồng', 'Lâm Đồng', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Lạng Sơn', 'Lạng Sơn', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Lào Cai', 'Lào Cai', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Long An', 'Long An', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Nam Định', 'Nam Định', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Nghệ An', 'Nghệ An', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Ninh Bình', 'Ninh Bình', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Ninh Thuận', 'Ninh Thuận', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Phú Thọ', 'Phú Thọ', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Phú Yên', 'Phú Yên', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Quảng Bình', 'Quảng Bình', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Quảng Nam', 'Quảng Nam', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Quảng Ngãi', 'Quảng Ngãi', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Quảng Ninh', 'Quảng Ninh', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Quảng Trị', 'Quảng Trị', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Sóc Trăng', 'Sóc Trăng', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Sơn La', 'Sơn La', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Tây Ninh', 'Tây Ninh', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Thái Bình', 'Thái Bình', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Thái Nguyên', 'Thái Nguyên', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Thanh Hóa', 'Thanh Hóa', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Thừa Thiên Huế', 'Thừa Thiên Huế', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Tiền Giang', 'Tiền Giang', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh TP. Hồ Chí Minh', 'Hồ Chí Minh', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Trà Vinh', 'Trà Vinh', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Tuyên Quang', 'Tuyên Quang', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Vĩnh Long', 'Vĩnh Long', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Vĩnh Phúc', 'Vĩnh Phúc', '', '', '', 'ACTIVE','POST_OFFICE'),
('Chi nhánh Yên Bái', 'Yên Bái', '', '', '', 'ACTIVE','POST_OFFICE');


INSERT INTO t_shipping_rule (min_weight, max_weight, noi_tinh, lien_tinh) VALUES
(0, 0.5, 15000, 20000),
(0.5, 1, 20000, 30000),
(1, 3, 30000, 40000),
(3, 99999, 3000, 5000);

